# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(727, 224)
        Form.setMinimumSize(QtCore.QSize(727, 224))
        Form.setMaximumSize(QtCore.QSize(727, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/icons8-pizza-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(255, 124, 16);\n"
"QLabel {\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.gridLayout_5 = QtWidgets.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(197, 77, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.optionsLineEdit = QtWidgets.QLineEdit(self.frame)
        self.optionsLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.optionsLineEdit.setReadOnly(True)
        self.optionsLineEdit.setObjectName("optionsLineEdit")
        self.horizontalLayout.addWidget(self.optionsLineEdit)
        self.browseButton = QtWidgets.QPushButton(self.frame)
        self.browseButton.setStyleSheet("background-color: rgb(255, 173, 73);\n"
"color: rgb(0, 0, 0)")
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setStyleSheet("background-color: rgb(197, 77, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.crustLineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.crustLineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.crustLineEdit.setReadOnly(True)
        self.crustLineEdit.setObjectName("crustLineEdit")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.crustLineEdit)
        self.gridLayout.addLayout(self.formLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(197, 77, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cheeseLevelLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.cheeseLevelLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cheeseLevelLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cheeseLevelLineEdit.setReadOnly(True)
        self.cheeseLevelLineEdit.setObjectName("cheeseLevelLineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cheeseLevelLineEdit)
        self.gridLayout_4.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setStyleSheet("background-color: rgb(197, 77, 0);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.sauceLevelLineEdit = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sauceLevelLineEdit.sizePolicy().hasHeightForWidth())
        self.sauceLevelLineEdit.setSizePolicy(sizePolicy)
        self.sauceLevelLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.sauceLevelLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sauceLevelLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.sauceLevelLineEdit.setReadOnly(True)
        self.sauceLevelLineEdit.setObjectName("sauceLevelLineEdit")
        self.horizontalLayout_4.addWidget(self.sauceLevelLineEdit)
        self.sauceLineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.sauceLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.sauceLineEdit.setReadOnly(True)
        self.sauceLineEdit.setObjectName("sauceLineEdit")
        self.horizontalLayout_4.addWidget(self.sauceLineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.randomizeButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.randomizeButton.setFont(font)
        self.randomizeButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 173, 73);")
        self.randomizeButton.setObjectName("randomizeButton")
        self.verticalLayout_2.addWidget(self.randomizeButton)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMaximumSize(QtCore.QSize(380, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(197, 77, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.toppingNumSelect = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toppingNumSelect.sizePolicy().hasHeightForWidth())
        self.toppingNumSelect.setSizePolicy(sizePolicy)
        self.toppingNumSelect.setMinimumSize(QtCore.QSize(51, 29))
        self.toppingNumSelect.setMaximumSize(QtCore.QSize(51, 16777215))
        self.toppingNumSelect.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.toppingNumSelect.setObjectName("toppingNumSelect")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.toppingNumSelect)
        self.horizontalLayout_5.addLayout(self.formLayout_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.maxToppingsLineEdit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxToppingsLineEdit.sizePolicy().hasHeightForWidth())
        self.maxToppingsLineEdit.setSizePolicy(sizePolicy)
        self.maxToppingsLineEdit.setMinimumSize(QtCore.QSize(51, 29))
        self.maxToppingsLineEdit.setMaximumSize(QtCore.QSize(51, 29))
        self.maxToppingsLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.maxToppingsLineEdit.setReadOnly(True)
        self.maxToppingsLineEdit.setObjectName("maxToppingsLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maxToppingsLineEdit)
        self.horizontalLayout_5.addLayout(self.formLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.toppingsListWidget = QtWidgets.QListWidget(self.frame_2)
        self.toppingsListWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.toppingsListWidget.setAlternatingRowColors(False)
        self.toppingsListWidget.setObjectName("toppingsListWidget")
        self.gridLayout_3.addWidget(self.toppingsListWidget, 2, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 0, 2, 1, 1)
        self.frame_2.raise_()
        self.frame_5.raise_()
        self.frame_4.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Random Pizza Generator"))
        self.label_6.setText(_translate("Form", "Options File"))
        self.browseButton.setText(_translate("Form", "Browse..."))
        self.label.setText(_translate("Form", "Crust"))
        self.label_2.setText(_translate("Form", "Cheese Level"))
        self.label_3.setText(_translate("Form", "Sauce"))
        self.randomizeButton.setText(_translate("Form", "Randomize"))
        self.label_9.setText(_translate("Form", "Toppings"))
        self.label_7.setText(_translate("Form", "Chosen:"))
        self.label_8.setText(_translate("Form", "Max Available:"))
        self.toppingsListWidget.setSortingEnabled(False)

